export const searchSuggestion = [
  "formación sociocultural boliviana",
  "anatomía humana",
  "histología y embriología",
  "salud pública 1",
  "bioquímica médica",
  "fisiología humana",
  "anatomía patológica",
  "bacteriología y virología humana",
  "parasitología y micología médica",
  "salud pública 2",
  "farmacología y terapéutica",
  "cirugía 1",
  "fisiopatología",
  "semiología general",
  "infectología y medicina tropical",
  "salud pública 3",
  "anestesiología",
  "oftalmología",
  "cirugía 2",
  "traumatología y ortopedia",
  "medicina interna 1",
  "neurología",
  "psicopatología",
  "dermatología",
  "salud pública 4",
  "cirugía 3",
  "ginecología y obstetricia",
  "pediatría",
  "medicina interna 2",
  "otorinolaringología",
  "psiquiatría y salud mental",
  "medicina legal",
  "aguilar gonzales oscar",
  "aguilar justiniano javier oscar",
  "arauz barba maría elena",
  "arce justiniano jorge ronald",
  "aponte vargas josé luis",
  "bolívar guzmán rubén darío",
  "carlos iván quiroga",
  "chely de limpias elizabeth",
  "coronado guzmán jorge",
  "cuéllar landívar walter hugo",
  "dajer ulloa erika",
  "dorado quesada pedro rodolfo",
  "encinas justiniano leoncio",
  "flores reus ral eduardo",
  "hidalgo filipavichi maría elizabeth",
  "iriarte céspedes norberto",
  "israel araujo yuself jail",
  "laguna montaño raúl jhonny",
  "leaños hereria hernán omar",
  "machado justiniano juan josé",
  "maida vargas de morales tatiana",
  "méndez capovianco alberto",
  "molina mery rafael",
  "nogales stresic edmundo hilario",
  "oropeza claure josé adolfo",
  "osinaga garcía remberto",
  "ortiz céspedes daniel",
  "panoso gonzales katty olivia",
  "pedraza leaños raúl",
  "pinto guevara yandira",
  "quiróz peña martha",
  "rivas soruco felipe",
  "rivera márquez williams pedro",
  "rivero bolívar harold percy",
  "saavedra quintanilla juan a.",
  "sangüeza acosta ariel lionel",
  "sossa lino josé luis",
  "tapia ríos carmela",
  "terrazas gómez héctor mirko",
  "von borries kovac hugo",
  "zambrana balladares lilian",
  "david schusselberg chavez",
  "elva soto sanchez de montero",
  "maria pavez lizarraga de aranzazu",
  "tomas virgilio prieto barron",
  "edgar caballero ibañez",
  "jesus rodolfo serrano",
  "elba soto sanchez",
  "haroldo mendez de la fuente",
  "marcelo mendez rosales",
  "victor hugo vargas pereira",
  "germán toledo",
  "omar montero gandarilla",
  "javier alfredo alcazar almeida",
  "edgar sempertegui",
  "viruez soleto erwin",
  "vargas vanegas reinerio",
  "sánchez araos darío",
  "lic. reymi ferreira",
  "wilfredo anzoategui",
  "grover aguilar",
  "jorge fernando aparicio",
];
